### ISSUE TITLE
Question: does this library work with the SMS hash

### ISSUE THREAD

**Issue by hirbod** [wolfgio/react-native-android-sms-verification#88]
Hi,

the library looks extremely promising, but the documentation is lacking a bit.
Does this library need the use of the app hash string to be included in the SMS or does it work differently?

**Comment by shubhambathe1** [comment]
Hello @hirbod, this library is based on Android SMS Retriever API which allows you to perform SMS-based user verification in your Android app automatically, without requiring the user to manually type verification codes, and without requiring any extra app permissions. But to make this library work you need to have a specific format for you sms. The format you should use on your message is as follows:

1. The message should be less than 140 bytes.
2. The message should have the OTP code.
3. Your message should end with your app’s 11-character hash string.

The following is an example:-

`
Your OTP for app code is: 6647
`
`
u0tUcRo4UQ7
`

Hope this helps.

**Comment by hirbod** [comment]
Thanks @shubhambathe1 

I decided to use `react-native-sms-user-consent` instead, as I feel like it is less intrusive and actually a good thing to ask the user if the SMS content can be read.

**Comment by wolfgio** [comment]
I will try to improve the lib documentation
